#!/bin/sh

set -e

TEMP_FILE1=`mktemp -t pkgos-reqsdiff1.XXXXXX` || exit 1
TEMP_FILE2=`mktemp -t pkgos-reqsdiff1.XXXXXX` || exit 1
pkgos-show-control-depends >${TEMP_FILE1}
pkgos-parse-requirements >${TEMP_FILE2}
diff -u ${TEMP_FILE1} ${TEMP_FILE2}
rm -f ${TEMP_FILE1} ${TEMP_FILE2}
