.\" Contact akroshchenko@mirantis.com to correct errors or typos.
.TH man 8 "27 Apr 2016" "45.0" "pkgos-parse-requirements"
.SH NAME
pkgos-parse-requirements - output list of project requirements 

.SH SYNOPSIS
.B pkgos-parse-requirements 
[-h] [file_for_parsing]

.SH DESCRIPTION
This utility attempts to parse an OpenStack requirements.txt file as input, and
produce a list of Debian dependencies as output.

It takes the first argument as the file to parse. If this utility is called
without a parameter, it will attempt to read the requirements.txt and
test-requirements.txt file.

Note that this is far from perfect, and that you *WILL* need to manually check
for the dependencies.

.B *CASES OF MANUAL EDDITING*:
.PD 0
.TP
Some packages should never be in the dependencies in Debian as they are
included in Python (version 2 or 3). If you find one that is missing, just add
it to the BLACK_LIST(for missing packages of Python 2) and/or the
BLACK_LIST_PY3 (for missing packages of Python 3).

.SH OPTIONS
.IP -h 
output this page

.SH BUGS
No known bugs.

.SH AUTHOR
Script is written by Thomas Goirand <zigo@debian.org>
.PD 0
.TP
Man page is written by Andrii Kroshchenko <akroshchenko@mirantis.com>
